version: '3'
services:
  frontend:
    build: ./client
    ports:
      - '3000:80'
    depends_on:
      - backend
    stdin_open: true
    tty: true

  backend:
    build: ./server
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
